#!/bin/bash

redis-server --daemonize yes

cd /app/

export SECRET_KEY_BASE="$(RAILS_ENV=production rake secret)"

RAILS_ENV=production rake db:create
RAILS_ENV=production rake db:setup
RAILS_ENV=production rake db:migrate

RAILS_ENV=production rails s
