default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: toysweet_development

test:
  <<: *default
  database: toysweet_test

production:
  <<: *default
  database: toysweet_production
  username: toysweet
  password: <%= ENV['TOYSWEET_DATABASE_PASSWORD'] %>
