default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: toysweet_development

test:
  <<: *default
  database: toysweet_test

production:
  <<: *default
  database: toysweet_production
  username: postgres
  password: 0a2z1u4I
  host: 10.10.188.209
  port: 52672
