# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96a4681efe5157cb41ad4ff3d332635af0a4bfcdd4166676d952b65305f00d075a8e7737388e77abef1a3e21fec3084bfadccbee8c434a2aedc65ff0ee8edfda

test:
  secret_key_base: f3855b4e41e6c15817ae308a578e920abbddb192e5ab1067d15e1fef611b59fa44f4c46c0a9b3997eadf50de18745c35c8c389e973bd48255411437a02882258

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
